//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afiliacion
    {
        public long Id { get; set; }
        public System.DateTime FechaRadicado { get; set; }
        public string Cedula { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<int> Edad { get; set; }
        public decimal Valor { get; set; }
    }
}
