//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clase
    {
        public long Id { get; set; }
        public long IdConductor { get; set; }
        public System.DateTime FechaClase { get; set; }
        public string NombreInstructor { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFin { get; set; }
    
        public virtual Conductor Conductor { get; set; }
    }
}
