//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public long Id { get; set; }
        public string Placa { get; set; }
        public string Tipo { get; set; }
        public string Marca { get; set; }
        public string Color { get; set; }
        public long IdConductor { get; set; }
    
        public virtual Conductor Conductor { get; set; }
    }
}
